### PR TITLE
Email translation, French translation updated, and allow scroll on modal for smartphones and low resolution

### PR DESCRIPTION
**Pull request by yoancutillas**

### CODE REVIEW

**Comment by tareq1988** [comment]
Thanks for the pull request. 

I use spaces, instead of tabs, so it would need to be changed. Also, LESS was used here, so writing in the CSS file directly is not expected. 

Now, when a popup modal is opened, I would like to put in a fixed position in the screen, the background could be scrolled or could be fixed. But in your pull request, when a poup is opened, and when scrolled, the popup remains in the opened position and doesn't remain in the viewport, which I wouldn't merge here.

Also, if you haven't noticed, the help popup is hidden when in mobile view from the `responsive.less` file.

**Comment by yoancutillas** [comment]
OK thanks,

I didn't mean to go against your workflow, nor what you intended to do with modals.
But I do want to use you modals on smartphones (it's a great feature, why disable it for smartphone users ?) and I suggested you that solution to make it responsive and scrollable. But it can be something else, I just want it to work on mobile :)

Take at least the french translations and the translations fixes ;)

**Comment by tareq1988** [comment]
Because at that time I didn't have enough time to test the modal in mobile devices, that's why it was disabled ;)

One thing you could do, open the modal in full 100% width and height for mobile phones. So either they have to close the modal, or send email and close the modal, no scrolling.

**Comment by tareq1988** [comment]
Closing the pull request as it has conflicts and doesn't match all the requirements at this moment.

**Pull request closed without merging**
